### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by Ualas** [omeka-s-modules/DspaceConnector#62]
Hello, 

I'm running into this error when I try to use dSpace connector in my docker Omeka S and my dSpace 6.x.

Also, doesn't the connector needs to do authentication in dspace API to perform those queries?

```
2019-08-05T19:14:18+00:00 ERR (3): PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'value (type, lang, value, uri, is_public, resource_id, property_id, value_resour' at line 1 in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(332): Doctrine\ORM\EntityManager->flush()
#7 /var/www/html/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#8 /var/www/html/application/src/Api/Manager.php(97): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /var/www/html/modules/DspaceConnector/src/Job/Import.php(301): Omeka\Api\Manager->batchCreate('items', Array, Array, Array)
#10 /var/www/html/modules/DspaceConnector/src/Job/Import.php(87): DspaceConnector\Job\Import->createItems(Array)
#11 /var/www/html/modules/DspaceConnector/src/Job/Import.php(44): DspaceConnector\Job\Import->importCollection('/rest/collectio...')
#12 /var/www/html/application/src/Job/DispatchStrategy/Synchronous.php(34): DspaceConnector\Job\Import->perform()
#13 /var/www/html/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#14 /var/www/html/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#15 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'value (type, lang, value, uri, is_public, resource_id, property_id, value_resour' at line 1 in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(332): Doctrine\ORM\EntityManager->flush()
#6 /var/www/html/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#7 /var/www/html/application/src/Api/Manager.php(97): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /var/www/html/modules/DspaceConnector/src/Job/Import.php(301): Omeka\Api\Manager->batchCreate('items', Array, Array, Array)
#9 /var/www/html/modules/DspaceConnector/src/Job/Import.php(87): DspaceConnector\Job\Import->createItems(Array)
#10 /var/www/html/modules/DspaceConnector/src/Job/Import.php(44): DspaceConnector\Job\Import->importCollection('/rest/collectio...')
#11 /var/www/html/application/src/Job/DispatchStrategy/Synchronous.php(34): DspaceConnector\Job\Import->perform()
#12 /var/www/html/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#13 /var/www/html/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#14 {main}

Next Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO value (type, lang, value, uri, is_public, resource_id, property_id, value_resource_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["literal", null, "2019-06-13T19:28:20Z", null, 1, 1557, 7, null]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'value (type, lang, value, uri, is_public, resource_id, property_id, value_resour' at line 1 in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO val...', Array)
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(332): Doctrine\ORM\EntityManager->flush()
#7 /var/www/html/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#8 /var/www/html/application/src/Api/Manager.php(97): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /var/www/html/modules/DspaceConnector/src/Job/Import.php(301): Omeka\Api\Manager->batchCreate('items', Array, Array, Array)
#10 /var/www/html/modules/DspaceConnector/src/Job/Import.php(87): DspaceConnector\Job\Import->createItems(Array)
#11 /var/www/html/modules/DspaceConnector/src/Job/Import.php(44): DspaceConnector\Job\Import->importCollection('/rest/collectio...')
#12 /var/www/html/application/src/Job/DispatchStrategy/Synchronous.php(34): DspaceConnector\Job\Import->perform()
#13 /var/www/html/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#14 /var/www/html/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#15 {main}```

**Comment by Ualas** [comment]
I've installed Omeka-S manually using the release package. Now it is working, I think it was an Imagick issue.
